## Imports

In [3]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

## Read Data

In [4]:
data_df = pd.read_csv("titanic_engineered.csv")
data_df

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,Deck,Title,Age_Class,Relatives,Not_alone,Fare_Per_Person
0,0,3,0,2,1,0,0,0,8,1,6,1,0,0
1,1,1,1,5,1,0,5,1,3,3,5,1,0,2
2,1,3,1,3,0,0,0,0,8,2,9,0,1,0
3,1,1,1,5,1,0,5,0,3,3,5,1,0,2
4,0,3,0,5,0,0,1,0,8,1,15,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,0,3,0,0,2,0,8,5,6,0,1,2
887,1,1,1,2,0,0,4,0,2,2,2,0,1,4
888,0,3,1,4,1,2,3,0,8,2,12,3,0,0
889,1,1,0,3,0,0,4,1,3,1,3,0,1,4
890,0,3,0,4,0,0,0,2,8,1,12,0,1,0

## Split Data
X_train and y_train

In [ ]:
y = data_df['Survived']
X = data_df.drop(['Survived'], axis=1)

## Random Forest Classifier

In [ ]:
rf = RandomForestClassifier(n_estimators=100)